name: silver_support
description: "A cross-platform app connecting seniors with student volunteers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

  # UI
  cupertino_icons: ^1.0.8
  flutter_local_notifications: 19.4.0

  # Firebase Core
  firebase_core: ^3.0.0

  # Firebase Services
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_database: ^11.3.10
  firebase_messaging: ^15.0.0
  go_router: ^6.5.0
  rxdart: ^0.27.7
  shared_preferences: ^2.5.3
  flutter_svg: 
  wave: ^0.2.0

  # Optional (for future Face ID/biometrics support)
  local_auth: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/silversupport-icon.png
    - assets/onboarding-1.png
    - assets/onboarding-2.png
    - assets/onboarding-3.png
    - assets/bg.png


flutter_launcher_icons:
  image_path: "assets/silversupport-icon.png"
  android: true
  ios: true
  windows:
    generate: true
